<a href="https://colab.research.google.com/github/Sousan23/SC-sesi1/blob/main/2802513981_metodius%20valentino%20jordan%20soushan%20letson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print ("hello")

hello


sesi 1

In [5]:
import time
print(time.ctime())

Thu Feb  6 04:41:16 2025


In [7]:
z = "hello"
y = 20
c = 30.9
f = ["Apple", "berry"]

z, y, c, f,
print(z, y, c, f,)

hello 20 30.9 ['Apple', 'berry']


In [8]:
o = int(1)
y = int(2.8)
z = int("3")
j = str(20)

print (o, y, z, j,)

1 2 3 20


In [10]:
a = "hello"
b = " world"
c = a+b
print(c)

hello world


In [13]:
a = "hello world"
print(a[1])

print(len(a))

e
11


In [17]:
b = "BINUS Univ"
print(b[2:5])

c = "BINUS Univ"
print(b[:5])

a = "BINUS Univ"
print(b[2:])


NUS
BINUS
NUS Univ


In [24]:
a = "hello"
print(a.upper())

b = "hello"
print(b.lower())

c = "hello"
print(a.replace("h", "j"))

HELLO
hello
jello


In [26]:
nama = "jamie"
x = 17
string = "nama saya {} umur {}"

print (string.format(nama, x))

nama saya jamie umur 17


In [29]:
nama = "Grace"
for i in enumerate(nama):
  print(i)

(0, 'G')
(1, 'r')
(2, 'a')
(3, 'c')
(4, 'e')


In [37]:
def perbandingan (a,b):
  if a>b:
    print("a lebih dari b")
  elif a<b:
      print("a kurang dari b")
  else:
        print("a = b")

In [38]:
perbandingan (7,11)

a kurang dari b


In [51]:
i=1
while i<5:
   print(i)
   i += 1

1
2
3
4


In [53]:
i=1
for i in range(2,6):
  print(i)

2
3
4
5


In [62]:
for i in range(2,40):
  if i%2 == 0:
    print(str(i) + "ganep")
  else:
   print(str(i) + "genjil")

2ganep
3genjil
4ganep
5genjil
6ganep
7genjil
8ganep
9genjil
10ganep
11genjil
12ganep
13genjil
14ganep
15genjil
16ganep
17genjil
18ganep
19genjil
20ganep
21genjil
22ganep
23genjil
24ganep
25genjil
26ganep
27genjil
28ganep
29genjil
30ganep
31genjil
32ganep
33genjil
34ganep
35genjil
36ganep
37genjil
38ganep
39genjil


In [63]:
import numpy as np

In [64]:
x = np.array([[1, 2, 3], [3, 6, 7,]])
x

array([[1, 2, 3],
       [3, 6, 7]])

In [66]:
y = np.array([[2, 2, 2], [5, 6, 4,]])
y

array([[2, 2, 2],
       [5, 6, 4]])

In [67]:
print(x+y)

[[ 3  4  5]
 [ 8 12 11]]


In [68]:
data = np.array ([10, 9, 8, 7, 5, 6])

print("rata-rata:", np.mean(data))
print("maksimum:", np.max(data))
print("minimum:", np.min(data))
print("standar devisiasi", np.std(data))

rata-rata: 7.5
maksimum: 10
minimum: 5
standar devisiasi 1.707825127659933


In [3]:

def calculate(uas, uts, asg):
    final_score = (0.5 * uas) + (0.3 * uts) + (0.2 * asg)
    return final_score


def get_grade(score):
    if score >= 80:
        return "A"
    elif score >= 70:
        return "B"
    elif score >= 60:
        return "C"
    elif score >= 50:
        return "D"
    else:
        return "E"


username = input("Masukkan Username: ")
password = ""

while password != "Admin123":
    password = input("Masukkan Password: ")
    if password != "Admin123":
        print("Password salah! Silakan coba lagi.")

print("Login Berhasil!\n")


nama_siswa = input("Masukkan Nama Mahasiswa: ")
uas = int(input("Masukkan Nilai UAS: "))
uts = int(input("Masukkan Nilai UTS: "))
asg = int(input("Masukkan Nilai ASG: "))


final_score = calculate(uas, uts, asg)
grade = get_grade(final_score)


print("\n=== HASIL PERHITUNGAN ===")
print(f"Nama Mahasiswa: {nama_siswa}")
print(f"Final Score: {final_score:.2f}")
print(f"Grade: {grade}")

Masukkan Username: ben
Masukkan Password: Admin123
Login Berhasil!

Masukkan Nama Mahasiswa: benjamin
Masukkan Nilai UAS: 86
Masukkan Nilai UTS: 87
Masukkan Nilai ASG: 94

=== HASIL PERHITUNGAN ===
Nama Mahasiswa: benjamin
Final Score: 87.90
Grade: A
